[advisories]
vulnerability = "deny"
unmaintained = "all"
unsound = "all"
notice = "warn"
yanked = "warn"

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "MPL-2.0",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
]
deny = [
  "GPL-2.0",
  "GPL-3.0",
  "AGPL-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
allow = []
skip = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
