//! Fast feedback lane: the no-config fixtures, run stub-free (the dominant
//! per-fixture cost). Generated by `build.rs` from fixtures with no
//! `===config===` section, minus `tests/fast_lane_deny.txt`. Run with
//! `cargo fast-test` (single-process; nextest's per-test processes are far
//! slower here). Excluded from default nextest runs via `.config/nextest.toml`.
include!(concat!(env!("OUT_DIR"), "/fast_lane_tests.rs"));
