#!/usr/bin/env bash
# Regenerate tests/fast_lane_deny.txt — the no-config fixtures that DO need the
# stdlib stubs, and so must be held out of the stub-free fast lane.
#
# It runs the full `fixtures` binary once with the stubs disabled
# (MIR_NO_BUILTIN_STUBS=1); any no-config fixture that fails stub-free is, by
# definition, one that references a built-in symbol. Run this after adding a
# no-config fixture that uses a built-in, or whenever the fast lane goes red.
set -euo pipefail

CRATE="$(cd "$(dirname "$0")/../.." && pwd)"   # crates/mir-analyzer
FX="$CRATE/tests/fixtures"
DENY="$CRATE/tests/fast_lane_deny.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "running the fixtures suite stub-free…" >&2
MIR_NO_BUILTIN_STUBS=1 cargo nextest run -p mir-analyzer -E 'binary(fixtures)' \
  --no-fail-fast --status-level fail --test-threads 8 \
  2>"$TMP/run.err" 1>/dev/null || true

# Fixtures that FAILED stub-free — the panic line prints the absolute path.
grep -oE 'fixture /[^ ]+\.phpt FAILED' "$TMP/run.err" \
  | sed -E 's/^fixture //; s/ FAILED$//' | sort -u > "$TMP/failing.txt"

# No-config fixtures (absolute paths).
grep -rL '===config===' --include='*.phpt' "$FX" \
  | xargs -n1 readlink -f | sort -u > "$TMP/noconfig.txt"

# Denylist = (no-config ∩ failing-stub-free), as crate-relative paths.
{
  echo "# Auto-generated by tests/fast_lane/regen_denylist.sh — do not edit by hand."
  echo "# No-config fixtures that reference a built-in symbol and therefore need the"
  echo "# stdlib stubs, so the stub-free fast lane (tests/fast_lane.rs) holds them out."
  comm -12 "$TMP/noconfig.txt" "$TMP/failing.txt" | sed "s#^$CRATE/##" | sort
} > "$DENY"

echo "wrote $(grep -vc '^#' "$DENY") entries to $DENY" >&2
